namespace BrokerHub.Services;

public class Translator
{
    private readonly IHttpContextAccessor _http;
    public Translator(IHttpContextAccessor http) => _http = http;

    public string Lang =>
        _http.HttpContext?.Request.Cookies["lang"] == "en" ? "en" : "ar";

    public bool IsRtl => Lang == "ar";

    public string this[string key] =>
        Texts.TryGetValue(key, out var v) ? (Lang == "ar" ? v.ar : v.en) : key;
    public string Get(string key, string lang) =>
    Texts.TryGetValue(key, out var v) ? (lang == "en" ? v.en : v.ar) : key;

    // كل النصوص هنا. أي نص جديد بنضيفه في السطر بتاعه
    private static readonly Dictionary<string, (string ar, string en)> Texts = new()
    {
        ["site.name"] = ("Clientix", "Clientix"),
        ["lang.switch"] = ("English", "العربية"),
        ["hero.title"] = ("اتصل بأفضل شركات التسويق بسهولة", "Connect with the best marketing agencies, easily"),
        ["hero.subtitle"] = ("منصة وسيط موثوق بتجمع الشركات ووكالات التسويق في مكان واحد.",
                              "A trusted broker platform that brings businesses and marketing agencies together."),
        ["role.business"] = ("أدخل كشركة / Business", "Enter as a Business"),
        ["role.business.desc"] = ("اعرف كل وكالات التسويق وخدماتها، وكلّم الوسيط واحجز ميعاد.",
                                   "Browse marketing agencies and their services, chat with the broker, and book a meeting."),
        ["role.agency"] = ("أدخل كوكالة تسويق", "Enter as a Marketing Agency"),
        ["role.agency.desc"] = ("اعرض أعمالك وخدماتك قدام الشركات اللي بتدور عليك.",
                                   "Showcase your portfolio and services to businesses looking for you."),
        ["btn.continue"] = ("متابعة", "Continue"),
        ["footer.rights"] = ("جميع الحقوق محفوظة", "All rights reserved"),
        ["auth.login"] = ("تسجيل الدخول", "Login"),
        ["auth.register"] = ("إنشاء حساب", "Create account"),
        ["auth.logout"] = ("خروج", "Logout"),
        ["auth.name"] = ("الاسم", "Name"),
        ["auth.email"] = ("البريد الإلكتروني", "Email"),
        ["auth.password"] = ("كلمة المرور", "Password"),
        ["auth.noaccount"] = ("ليس لديك حساب؟", "Don't have an account?"),
        ["auth.haveaccount"] = ("لديك حساب بالفعل؟", "Already have an account?"),
        ["auth.invalid"] = ("البريد أو كلمة المرور غير صحيحة", "Invalid email or password"),
        ["auth.exists"] = ("هذا البريد مسجل بالفعل", "This email is already registered"),
        ["auth.weak"] = ("كلمة المرور يجب ألا تقل عن 6 أحرف", "Password must be at least 6 characters"),
        ["dash.welcome"] = ("أهلًا", "Welcome"),
        ["auth.google"] = ("المتابعة بحساب Google", "Continue with Google"),
        ["auth.or"] = ("أو", "or"),
        ["auth.forgot"] = ("نسيت كلمة المرور؟", "Forgot password?"),
        ["auth.unconfirmed"] = ("لازم تفعّل حسابك الأول من الرسالة اللي وصلتك على الإيميل", "Please confirm your email first. Check your inbox"),
        ["auth.resend"] = ("إعادة إرسال رسالة التفعيل", "Resend confirmation email"),
        ["auth.sent"] = ("تم إرسال الرسالة، راجع بريدك (وفولدر Spam)", "Email sent. Check your inbox (and Spam)"),
        ["auth.checkemail"] = ("تم إنشاء الحساب! أرسلنا لك رسالة تفعيل على بريدك، اضغط على الرابط بداخلها لتفعيل الحساب.",
                        "Account created! We sent a confirmation link to your email. Click it to activate your account."),
        ["auth.mailfail"] = ("تعذر إرسال الرسالة، حاول مرة أخرى", "Could not send the email, please try again"),
        ["auth.confirmed"] = ("تم تفعيل حسابك بنجاح 🎉", "Your account is confirmed 🎉"),
        ["auth.confirm.bad"] = ("رابط التفعيل غير صالح أو منتهي", "Invalid or expired confirmation link"),
        ["forgot.title"] = ("استعادة كلمة المرور", "Reset your password"),
        ["forgot.desc"] = ("اكتب بريدك وهنرسل لك رابط لتعيين كلمة مرور جديدة.", "Enter your email and we'll send you a link to set a new password."),
        ["forgot.send"] = ("إرسال الرابط", "Send link"),
        ["forgot.sent"] = ("لو البريد مسجل عندنا، هيوصلك رابط الاستعادة خلال دقائق.", "If this email is registered, a reset link is on its way."),
        ["reset.title"] = ("كلمة مرور جديدة", "New password"),
        ["reset.save"] = ("حفظ", "Save"),
        ["reset.done"] = ("تم تغيير كلمة المرور. تقدر تسجّل دخول دلوقتي.", "Password changed. You can log in now."),
        ["reset.bad"] = ("الرابط غير صالح أو منتهي", "Invalid or expired link"),
        ["mail.confirm.subject"] = ("فعّل حسابك في كلاينتيكس", "Confirm your Clientix account"),
        ["mail.confirm.body"] = ("أهلًا بك! اضغط على الزرار لتفعيل حسابك.", "Welcome! Click the button below to activate your account."),
        ["mail.confirm.btn"] = ("تفعيل الحساب", "Confirm account"),
        ["mail.reset.subject"] = ("استعادة كلمة المرور", "Reset your password"),
        ["mail.reset.body"] = ("طلبت استعادة كلمة المرور. الرابط صالح لمدة ساعة. لو ماطلبتش ده تجاهل الرسالة.",
                            "You requested a password reset. The link is valid for 1 hour. If this wasn't you, ignore this email."),
        ["mail.reset.btn"] = ("تعيين كلمة مرور جديدة", "Set new password"),
        ["agencies.title"] = ("وكالات التسويق", "Marketing Agencies"),
        ["agencies.empty"] = ("لا توجد وكالات حتى الآن", "No agencies yet"),
        ["agencies.chat"] = ("تحدث مع الوسيط", "Chat with the broker"),
        ["agencies.book"] = ("احجز ميعاد", "Book a meeting"),
        ["pf.title"] = ("بروفايل الشركة", "Company Profile"),
        ["pf.company"] = ("اسم الشركة", "Company name"),
        ["pf.about"] = ("نبذة عن الشركة", "About the company"),
        ["pf.services"] = ("الخدمات (افصل بينها بفاصلة)", "Services (comma separated)"),
        ["pf.city"] = ("المدينة", "City"),
        ["pf.founded"] = ("سنة التأسيس", "Founded year"),
        ["pf.team"] = ("عدد الموظفين", "Team size"),
        ["pf.website"] = ("الموقع الإلكتروني", "Website"),
        ["pf.instagram"] = ("رابط انستجرام", "Instagram link"),
        ["pf.linkedin"] = ("رابط لينكدإن", "LinkedIn link"),
        ["pf.logo"] = ("رابط اللوجو (صورة)", "Logo image URL"),
        ["pf.save"] = ("حفظ", "Save"),
        ["pf.saved"] = ("تم الحفظ بنجاح ✅", "Saved successfully ✅"),
        ["pf.works"] = ("أعمال الشركة", "Our work"),
        ["pf.addwork"] = ("إضافة عمل", "Add work"),
        ["pf.worktitle"] = ("عنوان العمل", "Work title"),
        ["pf.workdesc"] = ("وصف مختصر", "Short description"),
        ["pf.workimg"] = ("رابط صورة العمل", "Work image URL"),
        ["pf.worklink"] = ("رابط العمل (اختياري)", "Work link (optional)"),
        ["pf.delete"] = ("حذف", "Delete"),
        ["pf.view"] = ("عرض البروفايل", "View profile"),
        ["pf.viewpublic"] = ("شوف بروفايلك كما يراه العملاء", "See your profile as clients see it"),
        ["pf.nowork"] = ("لا توجد أعمال بعد", "No work added yet"),
        ["pf.notfound"] = ("الوكالة غير موجودة", "Agency not found"),
        ["pf.year"] = ("تأسست", "Founded"),
        ["pf.members"] = ("موظف", "team members"),
        ["pf.visit"] = ("زيارة", "Visit"),
        ["pf.back"] = ("رجوع", "Back"),
        ["bk.title"] = ("لوحة الوسيط", "Broker Dashboard"),
        ["bk.agencies"] = ("الوكالات", "Agencies"),
        ["bk.add"] = ("إضافة وكالة جديدة", "Add new agency"),
        ["bk.edit"] = ("تعديل", "Edit"),
        ["bk.delete"] = ("حذف الوكالة", "Delete agency"),
        ["bk.confirmdel"] = ("متأكد من حذف الوكالة؟ سيتم حذف بروفايلها وأعمالها.", "Delete this agency? Its profile and works will be removed."),
        ["bk.created"] = ("تمت إضافة الوكالة ✅", "Agency created ✅"),
        ["bk.deleted"] = ("تم حذف الوكالة", "Agency deleted"),
        ["bk.noagencies"] = ("لا توجد وكالات بعد", "No agencies yet"),
        ["bk.newtitle"] = ("وكالة جديدة", "New agency"),
        ["bk.manage"] = ("إدارة", "Manage"),
        ["ag.readonly"] = ("بروفايلك يديره الوسيط. للتعديل تواصل معه.", "Your profile is managed by the broker. Contact them to make changes."),
        ["pf.autofill.title"] = ("تعبئة تلقائية من ملف", "Autofill from a file"),
        ["pf.autofill.desc"] = ("ارفع CV أو Portfolio للشركة (PDF أو Word أو صورة) وهنملّا البيانات تلقائيًا، وانت تراجعها وتحفظ.",
                         "Upload the company's CV or portfolio (PDF, Word or image). We'll fill the form, you review and save."),
        ["pf.autofill.btn"] = ("استخراج البيانات", "Extract data"),
        ["pf.autofilled"] = ("تم ملء البيانات من الملف. راجعها وعدّلها ثم اضغط حفظ.", "Data filled from the file. Review, edit, then press Save."),
        ["pf.autofail"] = ("تعذر قراءة الملف. جرّب ملف تاني أو أدخل البيانات يدويًا.", "Could not read the file. Try another one or enter the data manually."),
        ["pf.nofile"] = ("اختر ملف أولًا", "Please choose a file first"),
        ["pf.manual"] = ("أو أدخل البيانات يدويًا", "Or enter the data manually"),
        ["pf.logofile"] = ("أو ارفع صورة اللوجو", "Or upload a logo image"),
        ["pf.workmedia"] = ("ارفع صورة أو فيديو أو ملف", "Upload an image, video or file"),
        ["pf.workmedia.hint"] = ("صور، فيديو (mp4/webm/mov)، PDF، Word، PowerPoint. حتى 100MB", "Images, video (mp4/webm/mov), PDF, Word, PowerPoint. Up to 100MB"),
        ["pf.openfile"] = ("فتح الملف", "Open file"),
        ["bk.seed"] = ("إضافة وكالات تجريبية", "Add demo agencies"),
        ["bk.seeded"] = ("تمت إضافة الوكالات التجريبية ✅", "Demo agencies added ✅"),
        ["nav.agencies"] = ("الوكالات", "Agencies"),
        ["n.visit"] = ("زائر جديد", "New visitor"),
        ["n.register"] = ("تسجيل حساب جديد", "New sign-up"),
        ["n.login"] = ("تسجيل دخول", "User signed in"),
        ["n.meeting"] = ("طلب ميعاد جديد", "New meeting request"),
        ["n.agency"] = ("تحديث وكالة", "Agency update"),
        ["n.chat"] = ("رسالة جديدة", "New message"),

        ["bk.sub"] = ("كل اللي بيحصل في المنصة في مكان واحد", "Everything happening on the platform in one place"),
        ["bk.meetings"] = ("المواعيد", "Meetings"),
        ["bk.pending"] = ("في انتظار موافقتك", "Waiting for your approval"),
        ["bk.nopending"] = ("لا توجد طلبات جديدة", "No new requests"),
        ["bk.upcoming"] = ("المواعيد القادمة", "Upcoming meetings"),
        ["bk.nomeet"] = ("لا توجد مواعيد مؤكدة", "No confirmed meetings"),
        ["bk.activity"] = ("النشاط والإشعارات", "Activity and notifications"),
        ["bk.readall"] = ("تعليم الكل كمقروء", "Mark all as read"),
        ["bk.nofeed"] = ("لا توجد إشعارات بعد", "No notifications yet"),
        ["bk.stat.agencies"] = ("وكالة", "Agencies"),
        ["bk.stat.businesses"] = ("شركة مسجلة", "Registered businesses"),
        ["bk.stat.pending"] = ("طلبات معلقة", "Pending requests"),
        ["bk.stat.visits"] = ("زيارات اليوم", "Visits today"),

        ["meet.approve"] = ("قبول", "Approve"),
        ["meet.reject"] = ("رفض", "Decline"),
        ["meet.cancel"] = ("إلغاء", "Cancel"),
        ["meet.updated"] = ("تم تحديث الميعاد ✅", "Meeting updated ✅"),
        ["meet.conflict"] = ("عندك ميعاد مؤكد في نفس الوقت", "You already have a confirmed meeting at this time"),
        ["meet.status.pending"] = ("في الانتظار", "Pending"),
        ["meet.status.approved"] = ("مؤكد", "Confirmed"),
        ["meet.status.rejected"] = ("مرفوض", "Declined"),
        ["meet.status.cancelled"] = ("ملغي", "Cancelled"),
        ["meet.book.title"] = ("احجز ميعاد مع الوسيط", "Book a meeting with the broker"),
        ["meet.about"] = ("بخصوص", "About"),
        ["meet.general"] = ("استشارة عامة", "General consultation"),
        ["meet.date"] = ("التاريخ والوقت", "Date and time"),
        ["meet.note"] = ("ملاحظات (اختياري)", "Notes (optional)"),
        ["meet.submit"] = ("إرسال الطلب", "Send request"),
        ["meet.sent"] = ("تم إرسال الطلب. هيوصلك إشعار لما الوسيط يرد.", "Request sent. You will be notified when the broker responds."),
        ["meet.past"] = ("اختر وقتًا بعد نصف ساعة من الآن على الأقل", "Pick a time at least 30 minutes from now"),
        ["meet.busy"] = ("الوقت ده محجوز، اختر وقتًا آخر", "That time is taken, please pick another"),
        ["meet.mine"] = ("مواعيدي", "My meetings"),
        ["meet.none"] = ("لا توجد مواعيد بعد", "No meetings yet"),

        ["mail.meet.subject"] = ("تحديث بخصوص ميعادك", "An update on your meeting"),
        ["mail.meet.ok"] = ("تم تأكيد ميعادك مع الوسيط:", "Your meeting with the broker is confirmed:"),
        ["mail.meet.no"] = ("للأسف تعذّر هذا الميعاد:", "Unfortunately this meeting could not go ahead:"),
        ["mail.open"] = ("فتح الموقع", "Open Clientix"),
        ["bz.sub"] = ("تابع مواعيدك واكتشف أفضل وكالات التسويق", "Track your meetings and discover top marketing agencies"),
        ["bz.browse"] = ("تصفح الوكالات", "Browse agencies"),
        ["bz.stat.upcoming"] = ("مواعيد قادمة", "Upcoming meetings"),
        ["bz.stat.pending"] = ("في انتظار الرد", "Awaiting reply"),
        ["bz.stat.total"] = ("إجمالي الطلبات", "Total requests"),
        ["bz.stat.agencies"] = ("وكالة متاحة", "Agencies available"),
        ["bz.next"] = ("ميعادك القادم", "Your next meeting"),
        ["bz.nonext"] = ("لا يوجد ميعاد قادم. احجز استشارة مع الوسيط.", "No upcoming meeting. Book a consultation with the broker."),
        ["bz.in"] = ("خلال", "In"),
        ["bz.days"] = ("يوم", "days"),
        ["bz.hours"] = ("ساعة", "hours"),
        ["bz.min"] = ("دقيقة", "min"),
        ["bz.now"] = ("يبدأ قريبًا", "Starting soon"),
        ["bz.waiting"] = ("في انتظار رد الوسيط", "Waiting for the broker"),
        ["bz.upcoming"] = ("المواعيد القادمة", "Upcoming meetings"),
        ["bz.history"] = ("آخر المواعيد", "Recent meetings"),
        ["bz.nohistory"] = ("لا توجد مواعيد سابقة", "No previous meetings"),
        ["bz.quick"] = ("إجراءات سريعة", "Quick actions"),
        ["bz.chat"] = ("محادثة مع الوسيط", "Chat with the broker"),
        ["bz.account"] = ("حسابي", "My account"),
        ["bz.role"] = ("حساب شركة", "Business account"),
        ["bz.discover"] = ("اكتشف الوكالات", "Discover agencies"),
        ["bz.all"] = ("عرض الكل", "View all"),
        ["chat.title"] = ("المحادثة مع الوسيط", "Chat with the broker"),
        ["chat.sub"] = ("اسأل عن أي وكالة أو خدمة والوسيط هيرد عليك", "Ask about any agency or service and the broker will reply"),
        ["chat.placeholder"] = ("اكتب رسالتك...", "Type your message..."),
        ["chat.send"] = ("إرسال", "Send"),
        ["chat.empty"] = ("ابدأ المحادثة، اكتب أول رسالة 👋", "Start the conversation, write your first message 👋"),
        ["chat.online"] = ("متصل", "Connected"),
        ["chat.connecting"] = ("جاري الاتصال...", "Connecting..."),
        ["chat.broker"] = ("الوسيط", "The broker"),
        ["chat.about"] = ("بخصوص", "About"),
        ["chat.prefill"] = ("أهلًا، مهتم بالتواصل مع", "Hi, I'm interested in"),
        ["chat.newmsg"] = ("رسالة جديدة من الوسيط", "New message from the broker"),
        ["bk.chat"] = ("المحادثات", "Conversations"),
        ["bk.chat.pick"] = ("اختر محادثة من القايمة", "Pick a conversation from the list"),
        ["bk.chat.none"] = ("لا توجد محادثات بعد", "No conversations yet"),
        ["nav.dashboard"] = ("لوحتي", "Dashboard"),
        ["nav.myprofile"] = ("بروفايلي", "My profile"),
        ["auth.agencynote"] = ("حسابات الوكالات بيعملها الوسيط. استخدم الإيميل والباسورد اللي وصلوك منه.",
                       "Agency accounts are created by the broker. Use the email and password you received."),
        ["ag.stat.works"] = ("عمل في البروفايل", "Works in profile"),
        ["ag.stat.meetings"] = ("مواعيد قادمة عليك", "Upcoming meetings about you"),
        ["ag.stat.services"] = ("خدمة", "Services"),
        ["ag.meetings"] = ("مواعيد مؤكدة بخصوصك", "Confirmed meetings about you"),
        ["ag.nomeet"] = ("لا توجد مواعيد مؤكدة بعد", "No confirmed meetings yet"),
        ["ag.profile"] = ("ملخص بروفايلك", "Your profile summary"),
        ["ag.who"] = ("العميل", "Client"),
        ["nav.chat"] = ("المحادثة", "Chat"),
        ["nav.alerts"] = ("الإشعارات", "Alerts"),
        ["n.approved"] = ("تم تأكيد ميعادك", "Meeting confirmed"),
        ["n.rejected"] = ("تعذّر ميعادك", "Meeting declined"),
        ["n.cancelled"] = ("تم إلغاء ميعاد", "Meeting cancelled"),
        ["n.reminder"] = ("تذكير بميعاد", "Meeting reminder"),

        ["rem.day"] = ("تذكير: ميعادك بعد 24 ساعة مع", "Reminder: your meeting is in 24 hours with"),
        ["rem.hour"] = ("تذكير: ميعادك بعد ساعة مع", "Reminder: your meeting starts in 1 hour with"),
        ["rem.day.subj"] = ("ميعادك بكرة", "Your meeting is tomorrow"),
        ["rem.hour.subj"] = ("ميعادك بعد ساعة", "Your meeting starts in 1 hour"),

        ["mail.meet.cancel"] = ("تم إلغاء ميعادك:", "Your meeting has been cancelled:"),
        ["mail.view"] = ("عرض الميعاد", "View meeting"),
        ["meet.addcal"] = ("أضف للتقويم", "Add to calendar"),
        ["meet.ics.title"] = ("ميعاد مع الوسيط - كلاينتيكس", "Meeting with the broker - Clientix"),
        ["meet.ics.alarm"] = ("تذكير بميعادك", "Meeting reminder"),

        ["notif.title"] = ("الإشعارات", "Notifications"),
        ["notif.none"] = ("لا توجد إشعارات بعد", "No notifications yet"),
        ["cal.name"] = ("مواعيد كلاينتيكس", "Clientix meetings"),
        ["cal.with"] = ("ميعاد مع", "Meeting with"),
        ["cal.pending"] = ("(في انتظار التأكيد)", "(awaiting confirmation)"),
        ["meet.gcal"] = ("أضف لجوجل كالندر", "Add to Google Calendar"),
        ["nav.calendar"] = ("ربط التقويم", "Sync calendar"),

        ["cal.title"] = ("ربط تقويم الموبايل", "Connect your phone calendar"),
        ["cal.sub"] = ("اشترك مرة واحدة، وكل مواعيدك على Clientix هتظهر في تقويم موبايلك لوحدها ومعاها تنبيهات.",
                  "Subscribe once and all your Clientix meetings appear in your phone calendar, with alerts."),
        ["cal.local"] = ("الاشتراك بيشتغل لما الموقع يبقى أونلاين، لأن جوجل وآبل مش بيوصلوا لـ localhost. للتجربة استخدمي Dev Tunnel أو ngrok.",
                  "Subscribing works once the site is online, since Google and Apple cannot reach localhost. To test, use a Dev Tunnel or ngrok."),
        ["cal.apple"] = ("iPhone / iPad / Mac", "iPhone / iPad / Mac"),
        ["cal.apple.d"] = ("اضغط اشتراك وهيفتح التقويم ويطلب منك التأكيد.", "Tap Subscribe and the Calendar app will ask you to confirm."),
        ["cal.google"] = ("Google Calendar (أندرويد)", "Google Calendar (Android)"),
        ["cal.google.d"] = ("هيفتح جوجل كالندر، اضغط إضافة وهيظهر في موبايلك تلقائيًا.", "Opens Google Calendar. Tap Add and it syncs to your phone automatically."),
        ["cal.manual"] = ("أو انسخ الرابط", "Or copy the link"),
        ["cal.manual.d"] = ("في أي تطبيق تقويم اختر إضافة تقويم من رابط (From URL) والصق الرابط.", "In any calendar app choose Add calendar from URL and paste this link."),
        ["cal.subscribe"] = ("اشتراك", "Subscribe"),
        ["cal.copy"] = ("نسخ", "Copy"),
        ["cal.copied"] = ("تم النسخ ✓", "Copied ✓"),
        ["cal.tips.title"] = ("عشان التنبيهات توصلك", "To receive the alerts"),
        ["cal.tips.1"] = ("كل ميعاد مؤكد فيه تنبيه قبل يوم وقبل ساعة، وبيشتغل تلقائيًا على iPhone.", "Every confirmed meeting has alerts 1 day and 1 hour before. On iPhone they work automatically."),
        ["cal.tips.2"] = ("في Google Calendar افتح إعدادات تقويم Clientix وضيف إشعارات قبل يوم وقبل ساعة (مرة واحدة)، لأن جوجل بتستخدم إعدادات التقويم بدل تنبيهات الملف.", "In Google Calendar open the Clientix calendar settings and add notifications 1 day and 1 hour before (one time), because Google uses the calendar's settings instead of the file's alerts."),
        ["cal.tips.3"] = ("أي ميعاد جديد أو إلغاء بيظهر في التقويم بعد فترة (آبل غالبًا خلال ساعة، وجوجل ممكن لحد يوم). الإيميل والإشعارات جوه الموقع لحظيين.", "New or cancelled meetings show up in the calendar after a while (Apple usually within an hour, Google up to a day). Email and in-site notifications are instant."),
        ["cal.tips.4"] = ("الرابط خاص بيك، متشاركوش مع حد.", "This link is private, do not share it."),
        ["notif.viewall"] = ("عرض كل الإشعارات", "View all notifications"),

        ["push.ask"] = ("فعّل الإشعارات عشان توصلك المواعيد والرسائل حتى لو الموقع مقفول", "Turn on notifications to get meetings and messages even when the site is closed"),
        ["push.enable"] = ("تفعيل", "Enable"),
        ["push.later"] = ("لاحقًا", "Later"),

        ["pwa.install"] = ("ثبّت التطبيق", "Install the app"),
        ["pwa.ios"] = ("على iPhone: اضغط زرار المشاركة ثم «إضافة إلى الشاشة الرئيسية» عشان تثبّت التطبيق وتفعّل الإشعارات.",
                   "On iPhone: tap Share, then \"Add to Home Screen\" to install the app and enable notifications."),

        ["gcal.title"] = ("ربط مباشر مع Google Calendar", "Direct Google Calendar link"),
        ["gcal.desc"] = ("اربط حسابك مرة واحدة، وأي ميعاد يتأكد بيتضاف لتقويمك فورًا ومعاه تنبيه قبل يوم وقبل ساعة، ولو اتلغى بيتمسح لوحده.",
                       "Connect once. Confirmed meetings are added to your calendar instantly with alerts 1 day and 1 hour before, and removed if cancelled."),
        ["gcal.connect"] = ("ربط Google Calendar", "Connect Google Calendar"),
        ["gcal.connected"] = ("مربوط", "Connected"),
        ["gcal.disconnect"] = ("فصل الربط", "Disconnect"),
        ["gcal.ok"] = ("تم الربط، ومواعيدك المؤكدة اتضافت لتقويمك ✅", "Connected. Your confirmed meetings were added to your calendar ✅"),
        ["gcal.denied"] = ("تعذّر الربط. تأكد إنك وافقت على إذن التقويم وجرّب تاني.", "Could not connect. Make sure you allowed calendar access and try again."),
        ["gcal.off"] = ("تم فصل الربط", "Disconnected"),
        ["home.btn.explore"] = ("تصفح الوكالات", "Browse agencies"),
        ["home.btn.signin"] = ("دخول / إنشاء حساب", "Sign in / Create account"),
        ["home.s1.t"] = ("تصفّح الوكالات", "Browse agencies"),
        ["home.s1.d"] = ("شوف وكالات التسويق المعتمدة وأعمالها وخدماتها من غير ما تسجّل.", "See vetted marketing agencies, their work and services, no sign-up needed."),
        ["home.s2.t"] = ("كلّم الوسيط", "Talk to the broker"),
        ["home.s2.d"] = ("سجّل حساب وابعت للوسيط احتياجك وهو يرشّح لك الوكالة المناسبة.", "Create an account and tell the broker what you need. They recommend the right agency."),
        ["home.s3.t"] = ("احجز ميعاد", "Book a meeting"),
        ["home.s3.d"] = ("اختار الوقت والوسيط يأكده، وهيجيلك تذكير وإشعار على موبايلك.", "Pick a time, the broker confirms it, and you get reminders and notifications on your phone."),
        ["home.cta.t"] = ("جاهز تبدأ؟", "Ready to start?"),
        ["home.cta.d"] = ("اعمل حساب لشركتك في دقيقة وكلّم الوسيط.", "Create your company account in a minute and talk to the broker."),
        ["home.cta.btn"] = ("إنشاء حساب شركة", "Create a company account"),
        ["pf.nocompany"] = ("اسم الشركة مطلوب", "Company name is required"),
    };

}