namespace BrokerHub.Services;

public class Translator
{
    private readonly IHttpContextAccessor _http;
    public Translator(IHttpContextAccessor http) => _http = http;

    public string Lang =>
        _http.HttpContext?.Request.Cookies["lang"] == "en" ? "en" : "ar";

    public bool IsRtl => Lang == "ar";

    public string this[string key] =>
        Texts.TryGetValue(key, out var v) ? (Lang == "ar" ? v.ar : v.en) : key;

    // كل النصوص هنا. أي نص جديد بنضيفه في السطر بتاعه
    private static readonly Dictionary<string, (string ar, string en)> Texts = new()
    {
        ["site.name"] = ("Clientix", "Clientix"),
        ["lang.switch"] = ("English", "العربية"),
        ["hero.title"] = ("اتصل بأفضل شركات التسويق بسهولة", "Connect with the best marketing agencies, easily"),
        ["hero.subtitle"] = ("منصة وسيط موثوق بتجمع الشركات ووكالات التسويق في مكان واحد.",
                              "A trusted broker platform that brings businesses and marketing agencies together."),
        ["role.business"] = ("أدخل كشركة / Business", "Enter as a Business"),
        ["role.business.desc"] = ("اعرف كل وكالات التسويق وخدماتها، وكلّم الوسيط واحجز ميعاد.",
                                   "Browse marketing agencies and their services, chat with the broker, and book a meeting."),
        ["role.agency"] = ("أدخل كوكالة تسويق", "Enter as a Marketing Agency"),
        ["role.agency.desc"] = ("اعرض أعمالك وخدماتك قدام الشركات اللي بتدور عليك.",
                                   "Showcase your portfolio and services to businesses looking for you."),
        ["btn.continue"] = ("متابعة", "Continue"),
        ["footer.rights"] = ("جميع الحقوق محفوظة", "All rights reserved"),
        ["auth.login"] = ("تسجيل الدخول", "Login"),
        ["auth.register"] = ("إنشاء حساب", "Create account"),
        ["auth.logout"] = ("خروج", "Logout"),
        ["auth.name"] = ("الاسم", "Name"),
        ["auth.email"] = ("البريد الإلكتروني", "Email"),
        ["auth.password"] = ("كلمة المرور", "Password"),
        ["auth.noaccount"] = ("ليس لديك حساب؟", "Don't have an account?"),
        ["auth.haveaccount"] = ("لديك حساب بالفعل؟", "Already have an account?"),
        ["auth.invalid"] = ("البريد أو كلمة المرور غير صحيحة", "Invalid email or password"),
        ["auth.exists"] = ("هذا البريد مسجل بالفعل", "This email is already registered"),
        ["auth.weak"] = ("كلمة المرور يجب ألا تقل عن 6 أحرف", "Password must be at least 6 characters"),
        ["dash.welcome"] = ("أهلًا", "Welcome"),
        ["auth.google"] = ("المتابعة بحساب Google", "Continue with Google"),
        ["auth.or"] = ("أو", "or"),
        ["auth.forgot"] = ("نسيت كلمة المرور؟", "Forgot password?"),
        ["auth.unconfirmed"] = ("لازم تفعّل حسابك الأول من الرسالة اللي وصلتك على الإيميل", "Please confirm your email first. Check your inbox"),
        ["auth.resend"] = ("إعادة إرسال رسالة التفعيل", "Resend confirmation email"),
        ["auth.sent"] = ("تم إرسال الرسالة، راجع بريدك (وفولدر Spam)", "Email sent. Check your inbox (and Spam)"),
        ["auth.checkemail"] = ("تم إنشاء الحساب! أرسلنا لك رسالة تفعيل على بريدك، اضغط على الرابط بداخلها لتفعيل الحساب.",
                        "Account created! We sent a confirmation link to your email. Click it to activate your account."),
        ["auth.mailfail"] = ("تعذر إرسال الرسالة، حاول مرة أخرى", "Could not send the email, please try again"),
        ["auth.confirmed"] = ("تم تفعيل حسابك بنجاح 🎉", "Your account is confirmed 🎉"),
        ["auth.confirm.bad"] = ("رابط التفعيل غير صالح أو منتهي", "Invalid or expired confirmation link"),
        ["forgot.title"] = ("استعادة كلمة المرور", "Reset your password"),
        ["forgot.desc"] = ("اكتب بريدك وهنرسل لك رابط لتعيين كلمة مرور جديدة.", "Enter your email and we'll send you a link to set a new password."),
        ["forgot.send"] = ("إرسال الرابط", "Send link"),
        ["forgot.sent"] = ("لو البريد مسجل عندنا، هيوصلك رابط الاستعادة خلال دقائق.", "If this email is registered, a reset link is on its way."),
        ["reset.title"] = ("كلمة مرور جديدة", "New password"),
        ["reset.save"] = ("حفظ", "Save"),
        ["reset.done"] = ("تم تغيير كلمة المرور. تقدر تسجّل دخول دلوقتي.", "Password changed. You can log in now."),
        ["reset.bad"] = ("الرابط غير صالح أو منتهي", "Invalid or expired link"),
        ["mail.confirm.subject"] = ("فعّل حسابك في كلاينتيكس", "Confirm your Clientix account"),
        ["mail.confirm.body"] = ("أهلًا بك! اضغط على الزرار لتفعيل حسابك.", "Welcome! Click the button below to activate your account."),
        ["mail.confirm.btn"] = ("تفعيل الحساب", "Confirm account"),
        ["mail.reset.subject"] = ("استعادة كلمة المرور", "Reset your password"),
        ["mail.reset.body"] = ("طلبت استعادة كلمة المرور. الرابط صالح لمدة ساعة. لو ماطلبتش ده تجاهل الرسالة.",
                            "You requested a password reset. The link is valid for 1 hour. If this wasn't you, ignore this email."),
        ["mail.reset.btn"] = ("تعيين كلمة مرور جديدة", "Set new password"),
        ["agencies.title"] = ("وكالات التسويق", "Marketing Agencies"),
        ["agencies.empty"] = ("لا توجد وكالات حتى الآن", "No agencies yet"),
        ["agencies.chat"] = ("تحدث مع الوسيط", "Chat with the broker"),
        ["agencies.book"] = ("احجز ميعاد", "Book a meeting"),
        ["pf.title"] = ("بروفايل الشركة", "Company Profile"),
        ["pf.company"] = ("اسم الشركة", "Company name"),
        ["pf.about"] = ("نبذة عن الشركة", "About the company"),
        ["pf.services"] = ("الخدمات (افصل بينها بفاصلة)", "Services (comma separated)"),
        ["pf.city"] = ("المدينة", "City"),
        ["pf.founded"] = ("سنة التأسيس", "Founded year"),
        ["pf.team"] = ("عدد الموظفين", "Team size"),
        ["pf.website"] = ("الموقع الإلكتروني", "Website"),
        ["pf.instagram"] = ("رابط انستجرام", "Instagram link"),
        ["pf.linkedin"] = ("رابط لينكدإن", "LinkedIn link"),
        ["pf.logo"] = ("رابط اللوجو (صورة)", "Logo image URL"),
        ["pf.save"] = ("حفظ", "Save"),
        ["pf.saved"] = ("تم الحفظ بنجاح ✅", "Saved successfully ✅"),
        ["pf.works"] = ("أعمال الشركة", "Our work"),
        ["pf.addwork"] = ("إضافة عمل", "Add work"),
        ["pf.worktitle"] = ("عنوان العمل", "Work title"),
        ["pf.workdesc"] = ("وصف مختصر", "Short description"),
        ["pf.workimg"] = ("رابط صورة العمل", "Work image URL"),
        ["pf.worklink"] = ("رابط العمل (اختياري)", "Work link (optional)"),
        ["pf.delete"] = ("حذف", "Delete"),
        ["pf.view"] = ("عرض البروفايل", "View profile"),
        ["pf.viewpublic"] = ("شوف بروفايلك كما يراه العملاء", "See your profile as clients see it"),
        ["pf.nowork"] = ("لا توجد أعمال بعد", "No work added yet"),
        ["pf.notfound"] = ("الوكالة غير موجودة", "Agency not found"),
        ["pf.year"] = ("تأسست", "Founded"),
        ["pf.members"] = ("موظف", "team members"),
        ["pf.visit"] = ("زيارة", "Visit"),
        ["pf.back"] = ("رجوع", "Back"),
        ["bk.title"] = ("لوحة الوسيط", "Broker Dashboard"),
        ["bk.agencies"] = ("الوكالات", "Agencies"),
        ["bk.add"] = ("إضافة وكالة جديدة", "Add new agency"),
        ["bk.edit"] = ("تعديل", "Edit"),
        ["bk.delete"] = ("حذف الوكالة", "Delete agency"),
        ["bk.confirmdel"] = ("متأكد من حذف الوكالة؟ سيتم حذف بروفايلها وأعمالها.", "Delete this agency? Its profile and works will be removed."),
        ["bk.created"] = ("تمت إضافة الوكالة ✅", "Agency created ✅"),
        ["bk.deleted"] = ("تم حذف الوكالة", "Agency deleted"),
        ["bk.noagencies"] = ("لا توجد وكالات بعد", "No agencies yet"),
        ["bk.newtitle"] = ("وكالة جديدة", "New agency"),
        ["bk.manage"] = ("إدارة", "Manage"),
        ["ag.readonly"] = ("بروفايلك يديره الوسيط. للتعديل تواصل معه.", "Your profile is managed by the broker. Contact them to make changes."),
        ["pf.autofill.title"] = ("تعبئة تلقائية من ملف", "Autofill from a file"),
        ["pf.autofill.desc"] = ("ارفع CV أو Portfolio للشركة (PDF أو Word أو صورة) وهنملّا البيانات تلقائيًا، وانت تراجعها وتحفظ.",
                         "Upload the company's CV or portfolio (PDF, Word or image). We'll fill the form, you review and save."),
        ["pf.autofill.btn"] = ("استخراج البيانات", "Extract data"),
        ["pf.autofilled"] = ("تم ملء البيانات من الملف. راجعها وعدّلها ثم اضغط حفظ.", "Data filled from the file. Review, edit, then press Save."),
        ["pf.autofail"] = ("تعذر قراءة الملف. جرّب ملف تاني أو أدخل البيانات يدويًا.", "Could not read the file. Try another one or enter the data manually."),
        ["pf.nofile"] = ("اختر ملف أولًا", "Please choose a file first"),
        ["pf.manual"] = ("أو أدخل البيانات يدويًا", "Or enter the data manually"),
        ["pf.logofile"] = ("أو ارفع صورة اللوجو", "Or upload a logo image"),
        ["pf.workmedia"] = ("ارفع صورة أو فيديو أو ملف", "Upload an image, video or file"),
        ["pf.workmedia.hint"] = ("صور، فيديو (mp4/webm/mov)، PDF، Word، PowerPoint. حتى 100MB", "Images, video (mp4/webm/mov), PDF, Word, PowerPoint. Up to 100MB"),
        ["pf.openfile"] = ("فتح الملف", "Open file"),
        ["bk.seed"] = ("إضافة وكالات تجريبية", "Add demo agencies"),
        ["bk.seeded"] = ("تمت إضافة الوكالات التجريبية ✅", "Demo agencies added ✅"),
        ["nav.agencies"] = ("الوكالات", "Agencies"),
        ["n.visit"] = ("زائر جديد", "New visitor"),
        ["n.register"] = ("تسجيل حساب جديد", "New sign-up"),
        ["n.login"] = ("تسجيل دخول", "User signed in"),
        ["n.meeting"] = ("طلب ميعاد جديد", "New meeting request"),
        ["n.agency"] = ("تحديث وكالة", "Agency update"),
        ["n.chat"] = ("رسالة جديدة", "New message"),

        ["bk.sub"] = ("كل اللي بيحصل في المنصة في مكان واحد", "Everything happening on the platform in one place"),
        ["bk.meetings"] = ("المواعيد", "Meetings"),
        ["bk.pending"] = ("في انتظار موافقتك", "Waiting for your approval"),
        ["bk.nopending"] = ("لا توجد طلبات جديدة", "No new requests"),
        ["bk.upcoming"] = ("المواعيد القادمة", "Upcoming meetings"),
        ["bk.nomeet"] = ("لا توجد مواعيد مؤكدة", "No confirmed meetings"),
        ["bk.activity"] = ("النشاط والإشعارات", "Activity and notifications"),
        ["bk.readall"] = ("تعليم الكل كمقروء", "Mark all as read"),
        ["bk.nofeed"] = ("لا توجد إشعارات بعد", "No notifications yet"),
        ["bk.stat.agencies"] = ("وكالة", "Agencies"),
        ["bk.stat.businesses"] = ("شركة مسجلة", "Registered businesses"),
        ["bk.stat.pending"] = ("طلبات معلقة", "Pending requests"),
        ["bk.stat.visits"] = ("زيارات اليوم", "Visits today"),

        ["meet.approve"] = ("قبول", "Approve"),
        ["meet.reject"] = ("رفض", "Decline"),
        ["meet.cancel"] = ("إلغاء", "Cancel"),
        ["meet.updated"] = ("تم تحديث الميعاد ✅", "Meeting updated ✅"),
        ["meet.conflict"] = ("عندك ميعاد مؤكد في نفس الوقت", "You already have a confirmed meeting at this time"),
        ["meet.status.pending"] = ("في الانتظار", "Pending"),
        ["meet.status.approved"] = ("مؤكد", "Confirmed"),
        ["meet.status.rejected"] = ("مرفوض", "Declined"),
        ["meet.status.cancelled"] = ("ملغي", "Cancelled"),
        ["meet.book.title"] = ("احجز ميعاد مع الوسيط", "Book a meeting with the broker"),
        ["meet.about"] = ("بخصوص", "About"),
        ["meet.general"] = ("استشارة عامة", "General consultation"),
        ["meet.date"] = ("التاريخ والوقت", "Date and time"),
        ["meet.note"] = ("ملاحظات (اختياري)", "Notes (optional)"),
        ["meet.submit"] = ("إرسال الطلب", "Send request"),
        ["meet.sent"] = ("تم إرسال الطلب. هيوصلك إشعار لما الوسيط يرد.", "Request sent. You will be notified when the broker responds."),
        ["meet.past"] = ("اختر وقتًا بعد نصف ساعة من الآن على الأقل", "Pick a time at least 30 minutes from now"),
        ["meet.busy"] = ("الوقت ده محجوز، اختر وقتًا آخر", "That time is taken, please pick another"),
        ["meet.mine"] = ("مواعيدي", "My meetings"),
        ["meet.none"] = ("لا توجد مواعيد بعد", "No meetings yet"),

        ["mail.meet.subject"] = ("تحديث بخصوص ميعادك", "An update on your meeting"),
        ["mail.meet.ok"] = ("تم تأكيد ميعادك مع الوسيط:", "Your meeting with the broker is confirmed:"),
        ["mail.meet.no"] = ("للأسف تعذّر هذا الميعاد:", "Unfortunately this meeting could not go ahead:"),
        ["mail.open"] = ("فتح الموقع", "Open Clientix"),
        ["bz.sub"] = ("تابع مواعيدك واكتشف أفضل وكالات التسويق", "Track your meetings and discover top marketing agencies"),
        ["bz.browse"] = ("تصفح الوكالات", "Browse agencies"),
        ["bz.stat.upcoming"] = ("مواعيد قادمة", "Upcoming meetings"),
        ["bz.stat.pending"] = ("في انتظار الرد", "Awaiting reply"),
        ["bz.stat.total"] = ("إجمالي الطلبات", "Total requests"),
        ["bz.stat.agencies"] = ("وكالة متاحة", "Agencies available"),
        ["bz.next"] = ("ميعادك القادم", "Your next meeting"),
        ["bz.nonext"] = ("لا يوجد ميعاد قادم. احجز استشارة مع الوسيط.", "No upcoming meeting. Book a consultation with the broker."),
        ["bz.in"] = ("خلال", "In"),
        ["bz.days"] = ("يوم", "days"),
        ["bz.hours"] = ("ساعة", "hours"),
        ["bz.min"] = ("دقيقة", "min"),
        ["bz.now"] = ("يبدأ قريبًا", "Starting soon"),
        ["bz.waiting"] = ("في انتظار رد الوسيط", "Waiting for the broker"),
        ["bz.upcoming"] = ("المواعيد القادمة", "Upcoming meetings"),
        ["bz.history"] = ("آخر المواعيد", "Recent meetings"),
        ["bz.nohistory"] = ("لا توجد مواعيد سابقة", "No previous meetings"),
        ["bz.quick"] = ("إجراءات سريعة", "Quick actions"),
        ["bz.chat"] = ("محادثة مع الوسيط", "Chat with the broker"),
        ["bz.account"] = ("حسابي", "My account"),
        ["bz.role"] = ("حساب شركة", "Business account"),
        ["bz.discover"] = ("اكتشف الوكالات", "Discover agencies"),
        ["bz.all"] = ("عرض الكل", "View all"),
        ["chat.title"] = ("المحادثة مع الوسيط", "Chat with the broker"),
        ["chat.sub"] = ("اسأل عن أي وكالة أو خدمة والوسيط هيرد عليك", "Ask about any agency or service and the broker will reply"),
        ["chat.placeholder"] = ("اكتب رسالتك...", "Type your message..."),
        ["chat.send"] = ("إرسال", "Send"),
        ["chat.empty"] = ("ابدأ المحادثة، اكتب أول رسالة 👋", "Start the conversation, write your first message 👋"),
        ["chat.online"] = ("متصل", "Connected"),
        ["chat.connecting"] = ("جاري الاتصال...", "Connecting..."),
        ["chat.broker"] = ("الوسيط", "The broker"),
        ["chat.about"] = ("بخصوص", "About"),
        ["chat.prefill"] = ("أهلًا، مهتم بالتواصل مع", "Hi, I'm interested in"),
        ["chat.newmsg"] = ("رسالة جديدة من الوسيط", "New message from the broker"),
        ["bk.chat"] = ("المحادثات", "Conversations"),
        ["bk.chat.pick"] = ("اختر محادثة من القايمة", "Pick a conversation from the list"),
        ["bk.chat.none"] = ("لا توجد محادثات بعد", "No conversations yet"),
        ["nav.dashboard"] = ("لوحتي", "Dashboard"),
        ["nav.myprofile"] = ("بروفايلي", "My profile"),
        ["auth.agencynote"] = ("حسابات الوكالات بيعملها الوسيط. استخدم الإيميل والباسورد اللي وصلوك منه.",
                       "Agency accounts are created by the broker. Use the email and password you received."),
        ["ag.stat.works"] = ("عمل في البروفايل", "Works in profile"),
        ["ag.stat.meetings"] = ("مواعيد قادمة عليك", "Upcoming meetings about you"),
        ["ag.stat.services"] = ("خدمة", "Services"),
        ["ag.meetings"] = ("مواعيد مؤكدة بخصوصك", "Confirmed meetings about you"),
        ["ag.nomeet"] = ("لا توجد مواعيد مؤكدة بعد", "No confirmed meetings yet"),
        ["ag.profile"] = ("ملخص بروفايلك", "Your profile summary"),
        ["ag.who"] = ("العميل", "Client"),
    };

}